version: "3.8"

services:
  # Your Next.js application service
  theminermag: # !!! This is the name you'll use in your Caddyfile reverse_proxy !!!
    build:
      context: . # Assuming your Dockerfile is in the same directory
      dockerfile: Dockerfile # Your Next.js Dockerfile
    env_file:
      - "/theminermag.env"
    volumes:
      # Mount a volume to persist the standalone build output and make it accessible to Caddy
      - nextjs_standalone_data:/app/.next/standalone

    # We don't expose ports to the host here if Caddy is in the same network
    # ports:
    #   - "3000" # Only expose internally to the docker network
    restart: "always"
    environment:
      - NODE_ENV=production
      - PORT=3000 # Ensure Next.js listens on this port

# Define the volumes
volumes:
  nextjs_standalone_data: # Volume to share Next.js standalone build output
