export const companies = [
    "MARA",
    "RIOT",
    "CORZ",
    "BTDR",
    "CLSK",
    "IREN",
    "HUT",
    "WULF",
    // "PHX",
    "CIFR",
    "FUFU",
    "BITF",
    "BTBT",
    "CAN",
    "CANG",
    // "HIVE",
    // "SDIG",
    "ARBK",
    // "BTCM",
    // "GRYP",
    // "SOS",
    // "SLNH",
    // "GREE",
    // "LMFA",
    // "MIGI",
    // "BTOG",
    // "DGHI",
    // "ANY",
];

export const nonNasdaqCompanies = ["PHX", "ARBK", "NB2", "HIVE" ]